#https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: "15s" #default = 1m 
  scrape_timeout: "10s" #default = 10s
  evaluation_interval: "15s" #default = 1m 

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - pg-cadvisor:8080

  - job_name: prometheus
    static_configs:
      - targets: ['pg-prometheus:9090']
        labels: 
          instance: prometheus

  #- job_name: 'docker'
  #       # metrics_path defaults to '/metrics'
  #       # scheme defaults to 'http'.
  #  static_configs:
  #    - targets: ['localhost:9323'] #bind in docker desktop engine config

  - job_name: netcore-hotel
    scrape_interval: 5s
    #metrics_path: /metrics #default = /metrics 
    #scheme: http #default = http
    static_configs:  
      - targets: ['hotel'] #use docker inner container port
        labels:
            instance: hotel
    #dns_sd_configs:
    #  - names:
    #    - 'tasks.web'
    #    type: 'A'
    #    port: 80
  - job_name: consul_node_exporter
    metrics_path: /metrics
    scheme: http
    consul_sd_configs:
      - server: consul-server-0:8500
        services:
          - node_exporter